export default {
	id: 'web-animations-1',
	title: 'Web Animations',
	link: 'web-animations-1',
	status: 'experimental',
	globals: {
		Animation: {
			link: '#the-animation-interface',
			mdnGroup: 'DOM',
			extends: 'EventTarget',
			members: [
				'id',
				'effect',
				'timeline',
				'startTime',
				'currentTime',
				'playbackRate',
				'playState',
				'replaceState',
				'pending',
				'ready',
				'finished',
				'onfinish',
				'oncancel',
				'onremove',
			],
			methods: ['cancel', 'finish', 'play', 'pause', 'updatePlaybackRate', 'reverse', 'persist', 'commitStyles'],
		},
		AnimationTimeline: {
			link: '#the-animationtimeline-interface',
			mdnGroup: 'DOM',
			members: ['currentTime'],
		},
		AnimationEffect: {
			link: '#animationeffect',
			mdnGroup: 'DOM',
			methods: ['getTiming', 'getComputedTiming', 'updateTiming'],
		},
		KeyframeEffect: {
			link: '#the-keyframeeffect-interface',
			mdnGroup: 'DOM',
			extends: 'AnimationEffect',
			members: [
				'target',
				'pseudoElement',
				'composite',
			],
			methods: ['getKeyframes', 'setKeyframes'],
		},
		Element: {
			link: '#the-animatable-interface-mixin',
			mdnGroup: 'DOM',
			methods: ['animate', 'getAnimations'],
		},
		document: {
			link: '#extensions-to-the-documentorshadowroot-interface-mixin',
			mdnGroup: 'DOM',
			properties: ['timeline'],
			functions: ['getAnimations'],
		},
		DocumentTimeline: {
			link: '#the-documenttimeline-interface',
			mdnGroup: 'DOM',
			extends: 'AnimationTimeline',
		},
		AnimationPlaybackEvent: {
			link: '#the-animationplaybackevent-interface',
			mdnGroup: 'DOM',
			extends: 'Event',
			members: ['currentTime', 'timelineTime'],
		},
	},
};
