export default {
	id: 'cssom-view-1',
	title: 'CSSOM View Module',
	link: 'cssom-view-1',
	status: 'experimental',
	properties: {
		'scroll-behavior': {
			link: '#smooth-scrolling',
			tests: ['auto', 'smooth '],
		},
	},
	globals: {
		window: {
			link: '#extensions-to-the-window-interface',
			mdnGroup: 'DOM',
			properties: [
				'screen',
				'innerWidth',
				'innerHeight',
				'scrollX',
				'pageXOffset',
				'scrollY',
				'pageYOffset',
				'screenX',
				'screenY',
				'outerWidth',
				'outerHeight',
				'devicePixelRatio',
			],
			functions: [
				'matchMedia',
				'moveTo',
				'moveBy',
				'resizeTo',
				'resizeBy',
				'scroll',
				'scrollTo',
				'scrollBy',
			],
		},
		MediaQueryList: {
			link: '#the-mediaquerylist-interface',
			mdnGroup: 'DOM',
			extends: 'EventTarget',
			members: ['media', 'matches', 'onchange'],
			methods: ['addListener', 'removeListener'],
		},
		MediaQueryListEvent: {
			link: '#mediaquerylistevent',
			mdnGroup: 'DOM',
			extends: 'Event',
			members: ['media', 'matches'],
		},
		Screen: {
			link: '#the-screen-interface',
			mdnGroup: 'DOM',
			members: [
				'availWidth',
				'availHeight',
				'width',
				'height',
				'colorDepth',
				'pixelDepth',
			],
		},
		document: {
			link: '#extensions-to-the-document-interface',
			mdnGroup: 'DOM',
			members: ['scrollingElement'],
			methods: [
				'elementFromPoint',
				'elementsFromPoint',
				'caretPositionFromPoint',
			],
		},
		CaretPosition: {
			link: '#caretposition',
			mdnGroup: 'DOM',
			members: ['offsetNode', 'offset'],
			methods: ['getClientRect'],
		},
		Element: {
			link: '#extension-to-the-element-interface',
			mdnGroup: 'DOM',
			members: [
				'scrollTop',
				'scrollLeft',
				'scrollWidth',
				'scrollHeight',
				'clientTop',
				'clientLeft',
				'clientWidth',
				'clientHeight',
			],
			methods: [
				'getClientRects',
				'getBoundingClientRect',
				'scrollIntoView',
				'scroll',
				'scrollTo',
				'scrollBy',
			],
		},
		HTMLElement: {
			link: '#extensions-to-the-htmlelement-interface',
			mdnGroup: 'DOM',
			members: [
				'offsetParent',
				'offsetTop',
				'offsetLeft',
				'offsetWidth',
				'offsetHeight',
			],
		},
		HTMLImageElement: {
			link: '#extensions-to-the-htmlimageelement-interface',
			mdnGroup: 'DOM',
			members: ['x', 'y'],
		},
		Range: {
			link: '#extensions-to-the-range-interface',
			mdnGroup: 'DOM',
			methods: ['getClientRects', 'getBoundingClientRect'],
		},
		MouseEvent: {
			link: '#extensions-to-the-mouseevent-interface',
			mdnGroup: 'DOM',
			members: [
				'screenX',
				'screenY',
				'pageX',
				'pageY',
				'clientX',
				'clientY',
				'x',
				'y',
				'offsetX',
				'offsetY',
			],
		},
		Text: {
			link: '#geometryutils',
			mdnGroup: 'DOM',
			methods: [
				'getBoxQuads',
				'convertQuadFromNode',
				'convertRectFromNode',
				'convertPointFromNode',
			],
		},
		CSSPseudoElement: {
			link: '#geometryutils',
			mdnGroup: 'DOM',
			methods: [
				'getBoxQuads',
				'convertQuadFromNode',
				'convertRectFromNode',
				'convertPointFromNode',
			],
		},
		VisualViewport: {
			link: '#the-visualviewport-interface',
			mdnGroup: 'DOM',
			extends: 'EventTarget',
			members: [
				'offsetLeft',
				'offsetTop',
				'pageLeft',
				'pageTop',
				'width',
				'height',
				'scale',
				'onresize',
				'onscroll',
				'onscrollend',
			],
		},
	},
};
