//! Generate the C header (`include/browser.h`) from this crate's `extern "C"` surface.

use std::path::PathBuf;

fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    // Workspace root is two levels up from crates/ffi.
    let header = PathBuf::from(&crate_dir)
        .join("../../include/browser.h")
        .canonicalize()
        .unwrap_or_else(|_| PathBuf::from(&crate_dir).join("../../include/browser.h"));

    if let Some(parent) = header.parent() {
        let _ = std::fs::create_dir_all(parent);
    }

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        pragma_once: true,
        cpp_compat: true,
        documentation: true,
        header: Some("// Generated by cbindgen from crates/ffi — do not edit by hand.".into()),
        // The progress-callback signature references `engine::FrameView`, defined in the `engine`
        // dependency. Parse that crate so the struct is emitted into the header (otherwise the
        // generated callback typedef would reference an undefined type).
        parse: cbindgen::ParseConfig {
            parse_deps: true,
            include: Some(vec!["engine".into()]),
            ..Default::default()
        },
        ..Default::default()
    };

    match cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
    {
        Ok(bindings) => {
            bindings.write_to_file(&header);
        }
        Err(e) => {
            // Don't fail the build if header generation hiccups; print for visibility.
            println!("cargo:warning=cbindgen failed to generate header: {e}");
        }
    }

    println!("cargo:rerun-if-changed=src/lib.rs");
}
