// Generated by cbindgen from crates/ffi — do not edit by hand.

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque engine handle. cbindgen emits this as a forward-declared struct.
 *
 * `last_link` retains the most recent `browser_engine_link_at` result so the `*const c_char`
 * returned to the caller stays valid until the next `browser_engine_link_at` call on this handle
 * (or until `browser_engine_free`).
 */
typedef struct Engine Engine;

/**
 * A borrowed, C-ABI view of the engine's RGBA8 (straight-alpha) framebuffer, handed to the
 * progressive-load frame callback. `pixels` points at the engine's own buffer and is valid ONLY
 * for the duration of the callback call (the engine reuses/reallocates it on the next paint), so a
 * callback must copy synchronously. A null `pixels` means "nothing painted".
 *
 * Layout matches the FFI crate's `Framebuffer` struct exactly (same field order/types) so the FFI
 * layer can forward callbacks without conversion.
 */
typedef struct FrameView {
  const uint8_t *pixels;
  uint32_t width;
  uint32_t height;
  uint32_t stride;
} FrameView;

/**
 * A borrowed view of the engine's RGBA8 (straight-alpha) framebuffer.
 * `stride` is bytes per row. A null `pixels` means "nothing rendered".
 */
typedef struct Framebuffer {
  const uint8_t *pixels;
  uint32_t width;
  uint32_t height;
  uint32_t stride;
} Framebuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new engine. Release with [`browser_engine_free`].
 */
struct Engine *browser_engine_new(void);

/**
 * Free an engine created by [`browser_engine_new`]. Null is a no-op.
 *
 * # Safety
 * `engine` must be a pointer returned by [`browser_engine_new`] and not used afterwards.
 */
void browser_engine_free(struct Engine *engine);

/**
 * Set the logical viewport size (points) and backing scale (e.g. 2.0 on Retina).
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
void browser_engine_set_viewport(struct Engine *engine,
                                 uint32_t width,
                                 uint32_t height,
                                 float scale);

/**
 * Install (or clear, with a null `cb`) the progressive-load frame callback. While set, the engine
 * invokes `cb(ctx, framebuffer)` SYNCHRONOUSLY from inside `browser_engine_load_url`, on the load
 * thread, each time it paints a partial frame as the page's HTML streams in (and once more for the
 * final frame). The `Framebuffer` pixels point at the engine's own buffer and are valid ONLY for
 * the duration of the callback call — copy them synchronously; do not retain the pointer. `ctx` is
 * passed through unchanged. Pass a null `cb` to disable progressive frames (the default).
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`]; `cb` (if non-null) must remain a
 * valid function pointer and `ctx` valid for the lifetime of every `browser_engine_load_url` call
 * made while the callback is installed.
 */
void browser_engine_set_progress_callback(struct Engine *engine,
                                          void (*cb)(void*, struct FrameView),
                                          void *ctx);

/**
 * Navigate to `url` (NUL-terminated UTF-8). Returns 0 on success, negative on error:
 * -1 fetch/network failure, -2 bad arguments.
 *
 * When a progress callback is installed via [`browser_engine_set_progress_callback`], this paints
 * and delivers partial frames synchronously as the page streams in, then the final frame.
 *
 * # Safety
 * `engine` must be a valid handle; `url` must be a valid NUL-terminated C string.
 */
int32_t browser_engine_load_url(struct Engine *engine, const char *url);

/**
 * Scroll the page by `dy` device pixels (positive scrolls content up / toward the end).
 * Clamped to the document bounds on the next render.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
void browser_engine_scroll_by(struct Engine *engine, float dy);

/**
 * The loaded page's `<title>` as a NUL-terminated UTF-8 C string, or null if none.
 *
 * Lifetime: owned by the engine handle (stored in `last_title`); valid until the next
 * `browser_engine_title` call on this handle or until `browser_engine_free`. Copy before reusing.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
const char *browser_engine_title(struct Engine *engine);

/**
 * Paint the current state and return a borrowed view of the framebuffer.
 * Valid until the next render/free on this handle.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
struct Framebuffer browser_engine_render(struct Engine *engine);

/**
 * Hit-test the most recently rendered page at framebuffer device-pixel `(x, y)`. If a link
 * (`<a href>`) is under that point, returns a NUL-terminated UTF-8 C string with the resolved
 * absolute URL; otherwise returns null.
 *
 * Lifetime: the returned pointer is owned by the engine handle (stored in `last_link`) and stays
 * valid until the next `browser_engine_link_at` call on this handle, or until
 * `browser_engine_free`. Copy it (e.g. via `String(cString:)`) before calling again.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
const char *browser_engine_link_at(struct Engine *engine, float x, float y);

/**
 * Dispatch a `click` into the live page JS at framebuffer device-pixel `(x, y)` (viewport-
 * relative). Fires the page's click handlers (with bubbling); if the DOM changed, returns 1 to
 * signal the caller should re-render. Returns 0 if nothing changed / no live runtime.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
int32_t browser_engine_dispatch_click(struct Engine *engine, float x, float y);

/**
 * Whether a text `<input>`/`<textarea>` is currently focused (so the UI should route keystrokes
 * into the page via [`browser_engine_dispatch_key`]). Returns 1 if focused, else 0.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
int32_t browser_engine_has_text_focus(struct Engine *engine);

/**
 * Deliver a key press to the focused text field's page JS. `key` is the DOM key value
 * (e.g. "a", "Backspace", "Enter") and `code` the physical key code (e.g. "KeyA"), both NUL-
 * terminated UTF-8. Updates the field value + fires keydown/input/keyup. Returns 1 if the DOM
 * changed (re-render), else 0.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`]; `key`/`code` valid C strings.
 */
int32_t browser_engine_dispatch_key(struct Engine *engine, const char *key, const char *code);

/**
 * Run any due timers / animation callbacks in the live page JS (drives `setTimeout`/`setInterval`/
 * `requestAnimationFrame` after load). Cheap no-op when nothing is due. Returns 1 if the DOM
 * changed (the caller should re-render), else 0.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
int32_t browser_engine_tick(struct Engine *engine);

/**
 * Move the pointer to framebuffer device-pixel `(x, y)` (viewport-relative): fires the page's
 * hover events (`mouseover`/`mouseout`/`mouseenter`/`mouseleave`/`mousemove`) as the node under
 * the pointer changes. Cheap no-op when the hovered node is unchanged. Returns 1 if the DOM
 * changed (re-render), else 0.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
int32_t browser_engine_dispatch_move(struct Engine *engine, float x, float y);

/**
 * Devtools console REPL: evaluate `code` (NUL-terminated UTF-8) in the live page JS and return a
 * NUL-terminated UTF-8 result/error string. Lifetime: owned by the engine (stored in `last_eval`),
 * valid until the next `browser_engine_console_eval` call or `browser_engine_free`.
 *
 * # Safety
 * `engine` must be a valid handle; `code` a valid C string.
 */
const char *browser_engine_console_eval(struct Engine *engine, const char *code);

/**
 * The current page's console + error lines, joined by '\n', as a NUL-terminated UTF-8 string
 * (for the devtools Console tab). Owned by the engine (`last_console`); valid until the next call.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
const char *browser_engine_console_text(struct Engine *engine);

/**
 * The current navigation's network activity as a JSON array string (for the devtools Network tab).
 * Owned by the engine (`last_netlog`); valid until the next call.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
const char *browser_engine_network_log(struct Engine *engine);

/**
 * Dispatch a raw mouse event (`kind` = "mousedown"/"mouseup"/"dblclick"/"contextmenu", NUL-
 * terminated UTF-8) to the node at device-pixel `(x, y)`. Returns 1 if the DOM changed.
 *
 * # Safety
 * `engine` must be a valid handle; `kind` a valid C string.
 */
int32_t browser_engine_dispatch_mouse(struct Engine *engine, const char *kind, float x, float y);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
