// Generated by cbindgen from crates/ffi — do not edit by hand.

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque engine handle. cbindgen emits this as a forward-declared struct.
 *
 * `last_link` retains the most recent `browser_engine_link_at` result so the `*const c_char`
 * returned to the caller stays valid until the next `browser_engine_link_at` call on this handle
 * (or until `browser_engine_free`).
 */
typedef struct Engine Engine;

/**
 * A borrowed view of the engine's RGBA8 (straight-alpha) framebuffer.
 * `stride` is bytes per row. A null `pixels` means "nothing rendered".
 */
typedef struct Framebuffer {
  const uint8_t *pixels;
  uint32_t width;
  uint32_t height;
  uint32_t stride;
} Framebuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new engine. Release with [`browser_engine_free`].
 */
struct Engine *browser_engine_new(void);

/**
 * Free an engine created by [`browser_engine_new`]. Null is a no-op.
 *
 * # Safety
 * `engine` must be a pointer returned by [`browser_engine_new`] and not used afterwards.
 */
void browser_engine_free(struct Engine *engine);

/**
 * Set the logical viewport size (points) and backing scale (e.g. 2.0 on Retina).
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
void browser_engine_set_viewport(struct Engine *engine,
                                 uint32_t width,
                                 uint32_t height,
                                 float scale);

/**
 * Navigate to `url` (NUL-terminated UTF-8). Returns 0 on success, negative on error:
 * -1 fetch/network failure, -2 bad arguments.
 *
 * # Safety
 * `engine` must be a valid handle; `url` must be a valid NUL-terminated C string.
 */
int32_t browser_engine_load_url(struct Engine *engine, const char *url);

/**
 * Scroll the page by `dy` device pixels (positive scrolls content up / toward the end).
 * Clamped to the document bounds on the next render.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
void browser_engine_scroll_by(struct Engine *engine, float dy);

/**
 * The loaded page's `<title>` as a NUL-terminated UTF-8 C string, or null if none.
 *
 * Lifetime: owned by the engine handle (stored in `last_title`); valid until the next
 * `browser_engine_title` call on this handle or until `browser_engine_free`. Copy before reusing.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
const char *browser_engine_title(struct Engine *engine);

/**
 * Paint the current state and return a borrowed view of the framebuffer.
 * Valid until the next render/free on this handle.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
struct Framebuffer browser_engine_render(struct Engine *engine);

/**
 * Hit-test the most recently rendered page at framebuffer device-pixel `(x, y)`. If a link
 * (`<a href>`) is under that point, returns a NUL-terminated UTF-8 C string with the resolved
 * absolute URL; otherwise returns null.
 *
 * Lifetime: the returned pointer is owned by the engine handle (stored in `last_link`) and stays
 * valid until the next `browser_engine_link_at` call on this handle, or until
 * `browser_engine_free`. Copy it (e.g. via `String(cString:)`) before calling again.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
const char *browser_engine_link_at(struct Engine *engine, float x, float y);

/**
 * Dispatch a `click` into the live page JS at framebuffer device-pixel `(x, y)` (viewport-
 * relative). Fires the page's click handlers (with bubbling); if the DOM changed, returns 1 to
 * signal the caller should re-render. Returns 0 if nothing changed / no live runtime.
 *
 * # Safety
 * `engine` must be a valid handle from [`browser_engine_new`].
 */
int32_t browser_engine_dispatch_click(struct Engine *engine, float x, float y);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
